export const KLASSRUUM_LOCAL_TEACHERS = [
  {
    id: "mr_klass",
    name: "Mr. Klass",
    subjectSpecialty: "Mathematics",
    imageUrl: "/images/teachers/man.png",
    teachingStyle: "step_by_step",
    defaultPace: "normal",
    explanationDepth: "detailed",
    encouragementStyle: "gentle",
    voice: {
      provider: "elevenlabs",
      localVoiceId: "male_calm_teacher_01",
      displayName: "Calm Mathematics Teacher",
      language: "en",
      tone: "calm",
      defaultSpeed: 0.92,
      pauseBetweenSentencesMs: 550,
    },
  },
  {
    id: "ms_amani",
    name: "Ms. Amani",
    subjectSpecialty: "Science",
    imageUrl: "/images/teachers/woman.png",
    teachingStyle: "visual",
    defaultPace: "normal",
    explanationDepth: "standard",
    encouragementStyle: "gentle",
    voice: {
      provider: "elevenlabs",
      localVoiceId: "female_warm_teacher_01",
      displayName: "Warm Science Teacher",
      language: "en",
      tone: "warm",
      defaultSpeed: 0.95,
      pauseBetweenSentencesMs: 500,
    },
  },
  {
    id: "teacher_grace",
    name: "Teacher Grace",
    subjectSpecialty: "Primary Learning",
    imageUrl: "/images/teachers/woman.png",
    teachingStyle: "extra_support",
    defaultPace: "slow",
    explanationDepth: "basic",
    encouragementStyle: "gentle",
    voice: {
      provider: "elevenlabs",
      localVoiceId: "female_gentle_primary_01",
      displayName: "Gentle Primary Teacher",
      language: "en",
      tone: "gentle",
      defaultSpeed: 0.88,
      pauseBetweenSentencesMs: 700,
    },
  },
  {
    id: "prof_daniel",
    name: "Professor Daniel",
    subjectSpecialty: "Advanced Studies",
    imageUrl: "/images/teachers/man.png",
    teachingStyle: "concept_first",
    defaultPace: "normal",
    explanationDepth: "advanced",
    encouragementStyle: "direct",
    voice: {
      provider: "elevenlabs",
      localVoiceId: "male_academic_lecturer_01",
      displayName: "Academic Lecturer",
      language: "en",
      tone: "academic",
      defaultSpeed: 1,
      pauseBetweenSentencesMs: 400,
    },
  },
] as const;
