/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as InstitutionsRegisterRouteImport } from './routes/institutions.register'
import { Route as DemoClassroomRouteImport } from './routes/demo.classroom'
import { Route as ClassroomLessonIdRouteImport } from './routes/classroom.$lessonId'
import { Route as ClassroomEnhancedLessonIdRouteImport } from './routes/classroom-enhanced.$lessonId'
import { Route as ClassroomDesignLessonIdRouteImport } from './routes/classroom-design.$lessonId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ClassroomSessionSessionIdRouteImport } from './routes/classroom.session.$sessionId'
import { Route as ClassroomPreviewLessonIdRouteImport } from './routes/classroom.preview.$lessonId'
import { Route as AuthenticatedTeacherStudentsRouteImport } from './routes/_authenticated/teacher.students'
import { Route as AuthenticatedTeacherSettingsRouteImport } from './routes/_authenticated/teacher.settings'
import { Route as AuthenticatedTeacherSessionsRouteImport } from './routes/_authenticated/teacher.sessions'
import { Route as AuthenticatedTeacherResourcesRouteImport } from './routes/_authenticated/teacher.resources'
import { Route as AuthenticatedTeacherLessonsRouteImport } from './routes/_authenticated/teacher.lessons'
import { Route as AuthenticatedTeacherDashboardRouteImport } from './routes/_authenticated/teacher.dashboard'
import { Route as AuthenticatedTeacherCoursesRouteImport } from './routes/_authenticated/teacher.courses'
import { Route as AuthenticatedTeacherAnalyticsRouteImport } from './routes/_authenticated/teacher.analytics'
import { Route as AuthenticatedStudentSettingsRouteImport } from './routes/_authenticated/student.settings'
import { Route as AuthenticatedStudentSessionsRouteImport } from './routes/_authenticated/student.sessions'
import { Route as AuthenticatedStudentSearchRouteImport } from './routes/_authenticated/student.search'
import { Route as AuthenticatedStudentResourcesRouteImport } from './routes/_authenticated/student.resources'
import { Route as AuthenticatedStudentQuizzesRouteImport } from './routes/_authenticated/student.quizzes'
import { Route as AuthenticatedStudentNotificationsRouteImport } from './routes/_authenticated/student.notifications'
import { Route as AuthenticatedStudentNotesRouteImport } from './routes/_authenticated/student.notes'
import { Route as AuthenticatedStudentMessagesRouteImport } from './routes/_authenticated/student.messages'
import { Route as AuthenticatedStudentLessonsRouteImport } from './routes/_authenticated/student.lessons'
import { Route as AuthenticatedStudentLearningPlanRouteImport } from './routes/_authenticated/student.learning-plan'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student.dashboard'
import { Route as AuthenticatedStudentCoursesRouteImport } from './routes/_authenticated/student.courses'
import { Route as AuthenticatedStudentClassroomsRouteImport } from './routes/_authenticated/student.classrooms'
import { Route as AuthenticatedStudentCalendarRouteImport } from './routes/_authenticated/student.calendar'
import { Route as AuthenticatedStudentAssignmentsRouteImport } from './routes/_authenticated/student.assignments'
import { Route as AuthenticatedStudentAchievementsRouteImport } from './routes/_authenticated/student.achievements'
import { Route as AuthenticatedStudentAccessRouteImport } from './routes/_authenticated/student.access'
import { Route as AuthenticatedInstitutionTeachersRouteImport } from './routes/_authenticated/institution.teachers'
import { Route as AuthenticatedInstitutionStudentsRouteImport } from './routes/_authenticated/institution.students'
import { Route as AuthenticatedInstitutionSettingsRouteImport } from './routes/_authenticated/institution.settings'
import { Route as AuthenticatedInstitutionSessionsRouteImport } from './routes/_authenticated/institution.sessions'
import { Route as AuthenticatedInstitutionResourcesRouteImport } from './routes/_authenticated/institution.resources'
import { Route as AuthenticatedInstitutionEnrollmentsRouteImport } from './routes/_authenticated/institution.enrollments'
import { Route as AuthenticatedInstitutionDashboardRouteImport } from './routes/_authenticated/institution.dashboard'
import { Route as AuthenticatedInstitutionCoursesRouteImport } from './routes/_authenticated/institution.courses'
import { Route as AuthenticatedInstitutionClassroomsRouteImport } from './routes/_authenticated/institution.classrooms'
import { Route as AuthenticatedInstitutionAnalyticsRouteImport } from './routes/_authenticated/institution.analytics'
import { Route as AuthenticatedInstitutionActivityRouteImport } from './routes/_authenticated/institution.activity'
import { Route as AuthenticatedTeacherCoursesCourseIdRouteImport } from './routes/_authenticated/teacher.courses.$courseId'
import { Route as AuthenticatedStudentSettingsProfileRouteImport } from './routes/_authenticated/student.settings.profile'
import { Route as AuthenticatedStudentResourcesResourceIdRouteImport } from './routes/_authenticated/student.resources.$resourceId'
import { Route as AuthenticatedStudentQuizzesQuizIdRouteImport } from './routes/_authenticated/student.quizzes.$quizId'
import { Route as AuthenticatedStudentNotesNoteIdRouteImport } from './routes/_authenticated/student.notes.$noteId'
import { Route as AuthenticatedStudentLessonsLessonIdRouteImport } from './routes/_authenticated/student.lessons.$lessonId'
import { Route as AuthenticatedStudentCoursesCourseIdRouteImport } from './routes/_authenticated/student.courses.$courseId'
import { Route as AuthenticatedStudentAiLessonNewRouteImport } from './routes/_authenticated/student.ai-lesson.new'
import { Route as AuthenticatedInstitutionResourcesUploadRouteImport } from './routes/_authenticated/institution.resources.upload'
import { Route as AuthenticatedInstitutionCoursesNewRouteImport } from './routes/_authenticated/institution.courses.new'
import { Route as AuthenticatedInstitutionCoursesCourseIdRouteImport } from './routes/_authenticated/institution.courses.$courseId'
import { Route as AuthenticatedTeacherLessonsLessonIdEditRouteImport } from './routes/_authenticated/teacher.lessons.$lessonId.edit'
import { Route as AuthenticatedTeacherCoursesCourseIdAnalyticsRouteImport } from './routes/_authenticated/teacher.courses.$courseId.analytics'
import { Route as AuthenticatedStudentSessionsSessionIdSummaryRouteImport } from './routes/_authenticated/student.sessions.$sessionId.summary'
import { Route as AuthenticatedStudentSessionsSessionIdReplayRouteImport } from './routes/_authenticated/student.sessions.$sessionId.replay'
import { Route as AuthenticatedStudentCoursesCourseIdLessonsRouteImport } from './routes/_authenticated/student.courses.$courseId.lessons'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/student/progress',
  path: '/student/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRegisterRoute = InstitutionsRegisterRouteImport.update({
  id: '/institutions/register',
  path: '/institutions/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClassroomRoute = DemoClassroomRouteImport.update({
  id: '/demo/classroom',
  path: '/demo/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomLessonIdRoute = ClassroomLessonIdRouteImport.update({
  id: '/classroom/$lessonId',
  path: '/classroom/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomEnhancedLessonIdRoute =
  ClassroomEnhancedLessonIdRouteImport.update({
    id: '/classroom-enhanced/$lessonId',
    path: '/classroom-enhanced/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassroomDesignLessonIdRoute = ClassroomDesignLessonIdRouteImport.update({
  id: '/classroom-design/$lessonId',
  path: '/classroom-design/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClassroomSessionSessionIdRoute =
  ClassroomSessionSessionIdRouteImport.update({
    id: '/classroom/session/$sessionId',
    path: '/classroom/session/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClassroomPreviewLessonIdRoute =
  ClassroomPreviewLessonIdRouteImport.update({
    id: '/classroom/preview/$lessonId',
    path: '/classroom/preview/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTeacherStudentsRoute =
  AuthenticatedTeacherStudentsRouteImport.update({
    id: '/teacher/students',
    path: '/teacher/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherSettingsRoute =
  AuthenticatedTeacherSettingsRouteImport.update({
    id: '/teacher/settings',
    path: '/teacher/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherSessionsRoute =
  AuthenticatedTeacherSessionsRouteImport.update({
    id: '/teacher/sessions',
    path: '/teacher/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherResourcesRoute =
  AuthenticatedTeacherResourcesRouteImport.update({
    id: '/teacher/resources',
    path: '/teacher/resources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherLessonsRoute =
  AuthenticatedTeacherLessonsRouteImport.update({
    id: '/teacher/lessons',
    path: '/teacher/lessons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherDashboardRoute =
  AuthenticatedTeacherDashboardRouteImport.update({
    id: '/teacher/dashboard',
    path: '/teacher/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesRoute =
  AuthenticatedTeacherCoursesRouteImport.update({
    id: '/teacher/courses',
    path: '/teacher/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherAnalyticsRoute =
  AuthenticatedTeacherAnalyticsRouteImport.update({
    id: '/teacher/analytics',
    path: '/teacher/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentSettingsRoute =
  AuthenticatedStudentSettingsRouteImport.update({
    id: '/student/settings',
    path: '/student/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentSessionsRoute =
  AuthenticatedStudentSessionsRouteImport.update({
    id: '/student/sessions',
    path: '/student/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentSearchRoute =
  AuthenticatedStudentSearchRouteImport.update({
    id: '/student/search',
    path: '/student/search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentResourcesRoute =
  AuthenticatedStudentResourcesRouteImport.update({
    id: '/student/resources',
    path: '/student/resources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentQuizzesRoute =
  AuthenticatedStudentQuizzesRouteImport.update({
    id: '/student/quizzes',
    path: '/student/quizzes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentNotificationsRoute =
  AuthenticatedStudentNotificationsRouteImport.update({
    id: '/student/notifications',
    path: '/student/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentNotesRoute =
  AuthenticatedStudentNotesRouteImport.update({
    id: '/student/notes',
    path: '/student/notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentMessagesRoute =
  AuthenticatedStudentMessagesRouteImport.update({
    id: '/student/messages',
    path: '/student/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentLessonsRoute =
  AuthenticatedStudentLessonsRouteImport.update({
    id: '/student/lessons',
    path: '/student/lessons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentLearningPlanRoute =
  AuthenticatedStudentLearningPlanRouteImport.update({
    id: '/student/learning-plan',
    path: '/student/learning-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/student/dashboard',
    path: '/student/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCoursesRoute =
  AuthenticatedStudentCoursesRouteImport.update({
    id: '/student/courses',
    path: '/student/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentClassroomsRoute =
  AuthenticatedStudentClassroomsRouteImport.update({
    id: '/student/classrooms',
    path: '/student/classrooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCalendarRoute =
  AuthenticatedStudentCalendarRouteImport.update({
    id: '/student/calendar',
    path: '/student/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentAssignmentsRoute =
  AuthenticatedStudentAssignmentsRouteImport.update({
    id: '/student/assignments',
    path: '/student/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentAchievementsRoute =
  AuthenticatedStudentAchievementsRouteImport.update({
    id: '/student/achievements',
    path: '/student/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentAccessRoute =
  AuthenticatedStudentAccessRouteImport.update({
    id: '/student/access',
    path: '/student/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionTeachersRoute =
  AuthenticatedInstitutionTeachersRouteImport.update({
    id: '/institution/teachers',
    path: '/institution/teachers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionStudentsRoute =
  AuthenticatedInstitutionStudentsRouteImport.update({
    id: '/institution/students',
    path: '/institution/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionSettingsRoute =
  AuthenticatedInstitutionSettingsRouteImport.update({
    id: '/institution/settings',
    path: '/institution/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionSessionsRoute =
  AuthenticatedInstitutionSessionsRouteImport.update({
    id: '/institution/sessions',
    path: '/institution/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionResourcesRoute =
  AuthenticatedInstitutionResourcesRouteImport.update({
    id: '/institution/resources',
    path: '/institution/resources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionEnrollmentsRoute =
  AuthenticatedInstitutionEnrollmentsRouteImport.update({
    id: '/institution/enrollments',
    path: '/institution/enrollments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionDashboardRoute =
  AuthenticatedInstitutionDashboardRouteImport.update({
    id: '/institution/dashboard',
    path: '/institution/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionCoursesRoute =
  AuthenticatedInstitutionCoursesRouteImport.update({
    id: '/institution/courses',
    path: '/institution/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionClassroomsRoute =
  AuthenticatedInstitutionClassroomsRouteImport.update({
    id: '/institution/classrooms',
    path: '/institution/classrooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionAnalyticsRoute =
  AuthenticatedInstitutionAnalyticsRouteImport.update({
    id: '/institution/analytics',
    path: '/institution/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionActivityRoute =
  AuthenticatedInstitutionActivityRouteImport.update({
    id: '/institution/activity',
    path: '/institution/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherCoursesCourseIdRoute =
  AuthenticatedTeacherCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedTeacherCoursesRoute,
  } as any)
const AuthenticatedStudentSettingsProfileRoute =
  AuthenticatedStudentSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentSettingsRoute,
  } as any)
const AuthenticatedStudentResourcesResourceIdRoute =
  AuthenticatedStudentResourcesResourceIdRouteImport.update({
    id: '/$resourceId',
    path: '/$resourceId',
    getParentRoute: () => AuthenticatedStudentResourcesRoute,
  } as any)
const AuthenticatedStudentQuizzesQuizIdRoute =
  AuthenticatedStudentQuizzesQuizIdRouteImport.update({
    id: '/$quizId',
    path: '/$quizId',
    getParentRoute: () => AuthenticatedStudentQuizzesRoute,
  } as any)
const AuthenticatedStudentNotesNoteIdRoute =
  AuthenticatedStudentNotesNoteIdRouteImport.update({
    id: '/$noteId',
    path: '/$noteId',
    getParentRoute: () => AuthenticatedStudentNotesRoute,
  } as any)
const AuthenticatedStudentLessonsLessonIdRoute =
  AuthenticatedStudentLessonsLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => AuthenticatedStudentLessonsRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdRoute =
  AuthenticatedStudentCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedStudentCoursesRoute,
  } as any)
const AuthenticatedStudentAiLessonNewRoute =
  AuthenticatedStudentAiLessonNewRouteImport.update({
    id: '/student/ai-lesson/new',
    path: '/student/ai-lesson/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionResourcesUploadRoute =
  AuthenticatedInstitutionResourcesUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedInstitutionResourcesRoute,
  } as any)
const AuthenticatedInstitutionCoursesNewRoute =
  AuthenticatedInstitutionCoursesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInstitutionCoursesRoute,
  } as any)
const AuthenticatedInstitutionCoursesCourseIdRoute =
  AuthenticatedInstitutionCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedInstitutionCoursesRoute,
  } as any)
const AuthenticatedTeacherLessonsLessonIdEditRoute =
  AuthenticatedTeacherLessonsLessonIdEditRouteImport.update({
    id: '/$lessonId/edit',
    path: '/$lessonId/edit',
    getParentRoute: () => AuthenticatedTeacherLessonsRoute,
  } as any)
const AuthenticatedTeacherCoursesCourseIdAnalyticsRoute =
  AuthenticatedTeacherCoursesCourseIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedTeacherCoursesCourseIdRoute,
  } as any)
const AuthenticatedStudentSessionsSessionIdSummaryRoute =
  AuthenticatedStudentSessionsSessionIdSummaryRouteImport.update({
    id: '/$sessionId/summary',
    path: '/$sessionId/summary',
    getParentRoute: () => AuthenticatedStudentSessionsRoute,
  } as any)
const AuthenticatedStudentSessionsSessionIdReplayRoute =
  AuthenticatedStudentSessionsSessionIdReplayRouteImport.update({
    id: '/$sessionId/replay',
    path: '/$sessionId/replay',
    getParentRoute: () => AuthenticatedStudentSessionsRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdLessonsRoute =
  AuthenticatedStudentCoursesCourseIdLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedStudentCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/classroom-design/$lessonId': typeof ClassroomDesignLessonIdRoute
  '/classroom-enhanced/$lessonId': typeof ClassroomEnhancedLessonIdRoute
  '/classroom/$lessonId': typeof ClassroomLessonIdRoute
  '/demo/classroom': typeof DemoClassroomRoute
  '/institutions/register': typeof InstitutionsRegisterRoute
  '/student/progress': typeof StudentProgressRoute
  '/institution/activity': typeof AuthenticatedInstitutionActivityRoute
  '/institution/analytics': typeof AuthenticatedInstitutionAnalyticsRoute
  '/institution/classrooms': typeof AuthenticatedInstitutionClassroomsRoute
  '/institution/courses': typeof AuthenticatedInstitutionCoursesRouteWithChildren
  '/institution/dashboard': typeof AuthenticatedInstitutionDashboardRoute
  '/institution/enrollments': typeof AuthenticatedInstitutionEnrollmentsRoute
  '/institution/resources': typeof AuthenticatedInstitutionResourcesRouteWithChildren
  '/institution/sessions': typeof AuthenticatedInstitutionSessionsRoute
  '/institution/settings': typeof AuthenticatedInstitutionSettingsRoute
  '/institution/students': typeof AuthenticatedInstitutionStudentsRoute
  '/institution/teachers': typeof AuthenticatedInstitutionTeachersRoute
  '/student/access': typeof AuthenticatedStudentAccessRoute
  '/student/achievements': typeof AuthenticatedStudentAchievementsRoute
  '/student/assignments': typeof AuthenticatedStudentAssignmentsRoute
  '/student/calendar': typeof AuthenticatedStudentCalendarRoute
  '/student/classrooms': typeof AuthenticatedStudentClassroomsRoute
  '/student/courses': typeof AuthenticatedStudentCoursesRouteWithChildren
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/learning-plan': typeof AuthenticatedStudentLearningPlanRoute
  '/student/lessons': typeof AuthenticatedStudentLessonsRouteWithChildren
  '/student/messages': typeof AuthenticatedStudentMessagesRoute
  '/student/notes': typeof AuthenticatedStudentNotesRouteWithChildren
  '/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/student/quizzes': typeof AuthenticatedStudentQuizzesRouteWithChildren
  '/student/resources': typeof AuthenticatedStudentResourcesRouteWithChildren
  '/student/search': typeof AuthenticatedStudentSearchRoute
  '/student/sessions': typeof AuthenticatedStudentSessionsRouteWithChildren
  '/student/settings': typeof AuthenticatedStudentSettingsRouteWithChildren
  '/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/teacher/courses': typeof AuthenticatedTeacherCoursesRouteWithChildren
  '/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher/lessons': typeof AuthenticatedTeacherLessonsRouteWithChildren
  '/teacher/resources': typeof AuthenticatedTeacherResourcesRoute
  '/teacher/sessions': typeof AuthenticatedTeacherSessionsRoute
  '/teacher/settings': typeof AuthenticatedTeacherSettingsRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsRoute
  '/classroom/preview/$lessonId': typeof ClassroomPreviewLessonIdRoute
  '/classroom/session/$sessionId': typeof ClassroomSessionSessionIdRoute
  '/institution/courses/$courseId': typeof AuthenticatedInstitutionCoursesCourseIdRoute
  '/institution/courses/new': typeof AuthenticatedInstitutionCoursesNewRoute
  '/institution/resources/upload': typeof AuthenticatedInstitutionResourcesUploadRoute
  '/student/ai-lesson/new': typeof AuthenticatedStudentAiLessonNewRoute
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRouteWithChildren
  '/student/lessons/$lessonId': typeof AuthenticatedStudentLessonsLessonIdRoute
  '/student/notes/$noteId': typeof AuthenticatedStudentNotesNoteIdRoute
  '/student/quizzes/$quizId': typeof AuthenticatedStudentQuizzesQuizIdRoute
  '/student/resources/$resourceId': typeof AuthenticatedStudentResourcesResourceIdRoute
  '/student/settings/profile': typeof AuthenticatedStudentSettingsProfileRoute
  '/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRouteWithChildren
  '/student/courses/$courseId/lessons': typeof AuthenticatedStudentCoursesCourseIdLessonsRoute
  '/student/sessions/$sessionId/replay': typeof AuthenticatedStudentSessionsSessionIdReplayRoute
  '/student/sessions/$sessionId/summary': typeof AuthenticatedStudentSessionsSessionIdSummaryRoute
  '/teacher/courses/$courseId/analytics': typeof AuthenticatedTeacherCoursesCourseIdAnalyticsRoute
  '/teacher/lessons/$lessonId/edit': typeof AuthenticatedTeacherLessonsLessonIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/classroom-design/$lessonId': typeof ClassroomDesignLessonIdRoute
  '/classroom-enhanced/$lessonId': typeof ClassroomEnhancedLessonIdRoute
  '/classroom/$lessonId': typeof ClassroomLessonIdRoute
  '/demo/classroom': typeof DemoClassroomRoute
  '/institutions/register': typeof InstitutionsRegisterRoute
  '/student/progress': typeof StudentProgressRoute
  '/institution/activity': typeof AuthenticatedInstitutionActivityRoute
  '/institution/analytics': typeof AuthenticatedInstitutionAnalyticsRoute
  '/institution/classrooms': typeof AuthenticatedInstitutionClassroomsRoute
  '/institution/courses': typeof AuthenticatedInstitutionCoursesRouteWithChildren
  '/institution/dashboard': typeof AuthenticatedInstitutionDashboardRoute
  '/institution/enrollments': typeof AuthenticatedInstitutionEnrollmentsRoute
  '/institution/resources': typeof AuthenticatedInstitutionResourcesRouteWithChildren
  '/institution/sessions': typeof AuthenticatedInstitutionSessionsRoute
  '/institution/settings': typeof AuthenticatedInstitutionSettingsRoute
  '/institution/students': typeof AuthenticatedInstitutionStudentsRoute
  '/institution/teachers': typeof AuthenticatedInstitutionTeachersRoute
  '/student/access': typeof AuthenticatedStudentAccessRoute
  '/student/achievements': typeof AuthenticatedStudentAchievementsRoute
  '/student/assignments': typeof AuthenticatedStudentAssignmentsRoute
  '/student/calendar': typeof AuthenticatedStudentCalendarRoute
  '/student/classrooms': typeof AuthenticatedStudentClassroomsRoute
  '/student/courses': typeof AuthenticatedStudentCoursesRouteWithChildren
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/learning-plan': typeof AuthenticatedStudentLearningPlanRoute
  '/student/lessons': typeof AuthenticatedStudentLessonsRouteWithChildren
  '/student/messages': typeof AuthenticatedStudentMessagesRoute
  '/student/notes': typeof AuthenticatedStudentNotesRouteWithChildren
  '/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/student/quizzes': typeof AuthenticatedStudentQuizzesRouteWithChildren
  '/student/resources': typeof AuthenticatedStudentResourcesRouteWithChildren
  '/student/search': typeof AuthenticatedStudentSearchRoute
  '/student/sessions': typeof AuthenticatedStudentSessionsRouteWithChildren
  '/student/settings': typeof AuthenticatedStudentSettingsRouteWithChildren
  '/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/teacher/courses': typeof AuthenticatedTeacherCoursesRouteWithChildren
  '/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher/lessons': typeof AuthenticatedTeacherLessonsRouteWithChildren
  '/teacher/resources': typeof AuthenticatedTeacherResourcesRoute
  '/teacher/sessions': typeof AuthenticatedTeacherSessionsRoute
  '/teacher/settings': typeof AuthenticatedTeacherSettingsRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsRoute
  '/classroom/preview/$lessonId': typeof ClassroomPreviewLessonIdRoute
  '/classroom/session/$sessionId': typeof ClassroomSessionSessionIdRoute
  '/institution/courses/$courseId': typeof AuthenticatedInstitutionCoursesCourseIdRoute
  '/institution/courses/new': typeof AuthenticatedInstitutionCoursesNewRoute
  '/institution/resources/upload': typeof AuthenticatedInstitutionResourcesUploadRoute
  '/student/ai-lesson/new': typeof AuthenticatedStudentAiLessonNewRoute
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRouteWithChildren
  '/student/lessons/$lessonId': typeof AuthenticatedStudentLessonsLessonIdRoute
  '/student/notes/$noteId': typeof AuthenticatedStudentNotesNoteIdRoute
  '/student/quizzes/$quizId': typeof AuthenticatedStudentQuizzesQuizIdRoute
  '/student/resources/$resourceId': typeof AuthenticatedStudentResourcesResourceIdRoute
  '/student/settings/profile': typeof AuthenticatedStudentSettingsProfileRoute
  '/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRouteWithChildren
  '/student/courses/$courseId/lessons': typeof AuthenticatedStudentCoursesCourseIdLessonsRoute
  '/student/sessions/$sessionId/replay': typeof AuthenticatedStudentSessionsSessionIdReplayRoute
  '/student/sessions/$sessionId/summary': typeof AuthenticatedStudentSessionsSessionIdSummaryRoute
  '/teacher/courses/$courseId/analytics': typeof AuthenticatedTeacherCoursesCourseIdAnalyticsRoute
  '/teacher/lessons/$lessonId/edit': typeof AuthenticatedTeacherLessonsLessonIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/classroom-design/$lessonId': typeof ClassroomDesignLessonIdRoute
  '/classroom-enhanced/$lessonId': typeof ClassroomEnhancedLessonIdRoute
  '/classroom/$lessonId': typeof ClassroomLessonIdRoute
  '/demo/classroom': typeof DemoClassroomRoute
  '/institutions/register': typeof InstitutionsRegisterRoute
  '/student/progress': typeof StudentProgressRoute
  '/_authenticated/institution/activity': typeof AuthenticatedInstitutionActivityRoute
  '/_authenticated/institution/analytics': typeof AuthenticatedInstitutionAnalyticsRoute
  '/_authenticated/institution/classrooms': typeof AuthenticatedInstitutionClassroomsRoute
  '/_authenticated/institution/courses': typeof AuthenticatedInstitutionCoursesRouteWithChildren
  '/_authenticated/institution/dashboard': typeof AuthenticatedInstitutionDashboardRoute
  '/_authenticated/institution/enrollments': typeof AuthenticatedInstitutionEnrollmentsRoute
  '/_authenticated/institution/resources': typeof AuthenticatedInstitutionResourcesRouteWithChildren
  '/_authenticated/institution/sessions': typeof AuthenticatedInstitutionSessionsRoute
  '/_authenticated/institution/settings': typeof AuthenticatedInstitutionSettingsRoute
  '/_authenticated/institution/students': typeof AuthenticatedInstitutionStudentsRoute
  '/_authenticated/institution/teachers': typeof AuthenticatedInstitutionTeachersRoute
  '/_authenticated/student/access': typeof AuthenticatedStudentAccessRoute
  '/_authenticated/student/achievements': typeof AuthenticatedStudentAchievementsRoute
  '/_authenticated/student/assignments': typeof AuthenticatedStudentAssignmentsRoute
  '/_authenticated/student/calendar': typeof AuthenticatedStudentCalendarRoute
  '/_authenticated/student/classrooms': typeof AuthenticatedStudentClassroomsRoute
  '/_authenticated/student/courses': typeof AuthenticatedStudentCoursesRouteWithChildren
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/learning-plan': typeof AuthenticatedStudentLearningPlanRoute
  '/_authenticated/student/lessons': typeof AuthenticatedStudentLessonsRouteWithChildren
  '/_authenticated/student/messages': typeof AuthenticatedStudentMessagesRoute
  '/_authenticated/student/notes': typeof AuthenticatedStudentNotesRouteWithChildren
  '/_authenticated/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/_authenticated/student/quizzes': typeof AuthenticatedStudentQuizzesRouteWithChildren
  '/_authenticated/student/resources': typeof AuthenticatedStudentResourcesRouteWithChildren
  '/_authenticated/student/search': typeof AuthenticatedStudentSearchRoute
  '/_authenticated/student/sessions': typeof AuthenticatedStudentSessionsRouteWithChildren
  '/_authenticated/student/settings': typeof AuthenticatedStudentSettingsRouteWithChildren
  '/_authenticated/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/_authenticated/teacher/courses': typeof AuthenticatedTeacherCoursesRouteWithChildren
  '/_authenticated/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/_authenticated/teacher/lessons': typeof AuthenticatedTeacherLessonsRouteWithChildren
  '/_authenticated/teacher/resources': typeof AuthenticatedTeacherResourcesRoute
  '/_authenticated/teacher/sessions': typeof AuthenticatedTeacherSessionsRoute
  '/_authenticated/teacher/settings': typeof AuthenticatedTeacherSettingsRoute
  '/_authenticated/teacher/students': typeof AuthenticatedTeacherStudentsRoute
  '/classroom/preview/$lessonId': typeof ClassroomPreviewLessonIdRoute
  '/classroom/session/$sessionId': typeof ClassroomSessionSessionIdRoute
  '/_authenticated/institution/courses/$courseId': typeof AuthenticatedInstitutionCoursesCourseIdRoute
  '/_authenticated/institution/courses/new': typeof AuthenticatedInstitutionCoursesNewRoute
  '/_authenticated/institution/resources/upload': typeof AuthenticatedInstitutionResourcesUploadRoute
  '/_authenticated/student/ai-lesson/new': typeof AuthenticatedStudentAiLessonNewRoute
  '/_authenticated/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdRouteWithChildren
  '/_authenticated/student/lessons/$lessonId': typeof AuthenticatedStudentLessonsLessonIdRoute
  '/_authenticated/student/notes/$noteId': typeof AuthenticatedStudentNotesNoteIdRoute
  '/_authenticated/student/quizzes/$quizId': typeof AuthenticatedStudentQuizzesQuizIdRoute
  '/_authenticated/student/resources/$resourceId': typeof AuthenticatedStudentResourcesResourceIdRoute
  '/_authenticated/student/settings/profile': typeof AuthenticatedStudentSettingsProfileRoute
  '/_authenticated/teacher/courses/$courseId': typeof AuthenticatedTeacherCoursesCourseIdRouteWithChildren
  '/_authenticated/student/courses/$courseId/lessons': typeof AuthenticatedStudentCoursesCourseIdLessonsRoute
  '/_authenticated/student/sessions/$sessionId/replay': typeof AuthenticatedStudentSessionsSessionIdReplayRoute
  '/_authenticated/student/sessions/$sessionId/summary': typeof AuthenticatedStudentSessionsSessionIdSummaryRoute
  '/_authenticated/teacher/courses/$courseId/analytics': typeof AuthenticatedTeacherCoursesCourseIdAnalyticsRoute
  '/_authenticated/teacher/lessons/$lessonId/edit': typeof AuthenticatedTeacherLessonsLessonIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/classroom-design/$lessonId'
    | '/classroom-enhanced/$lessonId'
    | '/classroom/$lessonId'
    | '/demo/classroom'
    | '/institutions/register'
    | '/student/progress'
    | '/institution/activity'
    | '/institution/analytics'
    | '/institution/classrooms'
    | '/institution/courses'
    | '/institution/dashboard'
    | '/institution/enrollments'
    | '/institution/resources'
    | '/institution/sessions'
    | '/institution/settings'
    | '/institution/students'
    | '/institution/teachers'
    | '/student/access'
    | '/student/achievements'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/classrooms'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/learning-plan'
    | '/student/lessons'
    | '/student/messages'
    | '/student/notes'
    | '/student/notifications'
    | '/student/quizzes'
    | '/student/resources'
    | '/student/search'
    | '/student/sessions'
    | '/student/settings'
    | '/teacher/analytics'
    | '/teacher/courses'
    | '/teacher/dashboard'
    | '/teacher/lessons'
    | '/teacher/resources'
    | '/teacher/sessions'
    | '/teacher/settings'
    | '/teacher/students'
    | '/classroom/preview/$lessonId'
    | '/classroom/session/$sessionId'
    | '/institution/courses/$courseId'
    | '/institution/courses/new'
    | '/institution/resources/upload'
    | '/student/ai-lesson/new'
    | '/student/courses/$courseId'
    | '/student/lessons/$lessonId'
    | '/student/notes/$noteId'
    | '/student/quizzes/$quizId'
    | '/student/resources/$resourceId'
    | '/student/settings/profile'
    | '/teacher/courses/$courseId'
    | '/student/courses/$courseId/lessons'
    | '/student/sessions/$sessionId/replay'
    | '/student/sessions/$sessionId/summary'
    | '/teacher/courses/$courseId/analytics'
    | '/teacher/lessons/$lessonId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/classroom-design/$lessonId'
    | '/classroom-enhanced/$lessonId'
    | '/classroom/$lessonId'
    | '/demo/classroom'
    | '/institutions/register'
    | '/student/progress'
    | '/institution/activity'
    | '/institution/analytics'
    | '/institution/classrooms'
    | '/institution/courses'
    | '/institution/dashboard'
    | '/institution/enrollments'
    | '/institution/resources'
    | '/institution/sessions'
    | '/institution/settings'
    | '/institution/students'
    | '/institution/teachers'
    | '/student/access'
    | '/student/achievements'
    | '/student/assignments'
    | '/student/calendar'
    | '/student/classrooms'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/learning-plan'
    | '/student/lessons'
    | '/student/messages'
    | '/student/notes'
    | '/student/notifications'
    | '/student/quizzes'
    | '/student/resources'
    | '/student/search'
    | '/student/sessions'
    | '/student/settings'
    | '/teacher/analytics'
    | '/teacher/courses'
    | '/teacher/dashboard'
    | '/teacher/lessons'
    | '/teacher/resources'
    | '/teacher/sessions'
    | '/teacher/settings'
    | '/teacher/students'
    | '/classroom/preview/$lessonId'
    | '/classroom/session/$sessionId'
    | '/institution/courses/$courseId'
    | '/institution/courses/new'
    | '/institution/resources/upload'
    | '/student/ai-lesson/new'
    | '/student/courses/$courseId'
    | '/student/lessons/$lessonId'
    | '/student/notes/$noteId'
    | '/student/quizzes/$quizId'
    | '/student/resources/$resourceId'
    | '/student/settings/profile'
    | '/teacher/courses/$courseId'
    | '/student/courses/$courseId/lessons'
    | '/student/sessions/$sessionId/replay'
    | '/student/sessions/$sessionId/summary'
    | '/teacher/courses/$courseId/analytics'
    | '/teacher/lessons/$lessonId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/classroom-design/$lessonId'
    | '/classroom-enhanced/$lessonId'
    | '/classroom/$lessonId'
    | '/demo/classroom'
    | '/institutions/register'
    | '/student/progress'
    | '/_authenticated/institution/activity'
    | '/_authenticated/institution/analytics'
    | '/_authenticated/institution/classrooms'
    | '/_authenticated/institution/courses'
    | '/_authenticated/institution/dashboard'
    | '/_authenticated/institution/enrollments'
    | '/_authenticated/institution/resources'
    | '/_authenticated/institution/sessions'
    | '/_authenticated/institution/settings'
    | '/_authenticated/institution/students'
    | '/_authenticated/institution/teachers'
    | '/_authenticated/student/access'
    | '/_authenticated/student/achievements'
    | '/_authenticated/student/assignments'
    | '/_authenticated/student/calendar'
    | '/_authenticated/student/classrooms'
    | '/_authenticated/student/courses'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/learning-plan'
    | '/_authenticated/student/lessons'
    | '/_authenticated/student/messages'
    | '/_authenticated/student/notes'
    | '/_authenticated/student/notifications'
    | '/_authenticated/student/quizzes'
    | '/_authenticated/student/resources'
    | '/_authenticated/student/search'
    | '/_authenticated/student/sessions'
    | '/_authenticated/student/settings'
    | '/_authenticated/teacher/analytics'
    | '/_authenticated/teacher/courses'
    | '/_authenticated/teacher/dashboard'
    | '/_authenticated/teacher/lessons'
    | '/_authenticated/teacher/resources'
    | '/_authenticated/teacher/sessions'
    | '/_authenticated/teacher/settings'
    | '/_authenticated/teacher/students'
    | '/classroom/preview/$lessonId'
    | '/classroom/session/$sessionId'
    | '/_authenticated/institution/courses/$courseId'
    | '/_authenticated/institution/courses/new'
    | '/_authenticated/institution/resources/upload'
    | '/_authenticated/student/ai-lesson/new'
    | '/_authenticated/student/courses/$courseId'
    | '/_authenticated/student/lessons/$lessonId'
    | '/_authenticated/student/notes/$noteId'
    | '/_authenticated/student/quizzes/$quizId'
    | '/_authenticated/student/resources/$resourceId'
    | '/_authenticated/student/settings/profile'
    | '/_authenticated/teacher/courses/$courseId'
    | '/_authenticated/student/courses/$courseId/lessons'
    | '/_authenticated/student/sessions/$sessionId/replay'
    | '/_authenticated/student/sessions/$sessionId/summary'
    | '/_authenticated/teacher/courses/$courseId/analytics'
    | '/_authenticated/teacher/lessons/$lessonId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClassroomDesignLessonIdRoute: typeof ClassroomDesignLessonIdRoute
  ClassroomEnhancedLessonIdRoute: typeof ClassroomEnhancedLessonIdRoute
  ClassroomLessonIdRoute: typeof ClassroomLessonIdRoute
  DemoClassroomRoute: typeof DemoClassroomRoute
  InstitutionsRegisterRoute: typeof InstitutionsRegisterRoute
  StudentProgressRoute: typeof StudentProgressRoute
  ClassroomPreviewLessonIdRoute: typeof ClassroomPreviewLessonIdRoute
  ClassroomSessionSessionIdRoute: typeof ClassroomSessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/student/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/register': {
      id: '/institutions/register'
      path: '/institutions/register'
      fullPath: '/institutions/register'
      preLoaderRoute: typeof InstitutionsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/classroom': {
      id: '/demo/classroom'
      path: '/demo/classroom'
      fullPath: '/demo/classroom'
      preLoaderRoute: typeof DemoClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom/$lessonId': {
      id: '/classroom/$lessonId'
      path: '/classroom/$lessonId'
      fullPath: '/classroom/$lessonId'
      preLoaderRoute: typeof ClassroomLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom-enhanced/$lessonId': {
      id: '/classroom-enhanced/$lessonId'
      path: '/classroom-enhanced/$lessonId'
      fullPath: '/classroom-enhanced/$lessonId'
      preLoaderRoute: typeof ClassroomEnhancedLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom-design/$lessonId': {
      id: '/classroom-design/$lessonId'
      path: '/classroom-design/$lessonId'
      fullPath: '/classroom-design/$lessonId'
      preLoaderRoute: typeof ClassroomDesignLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/classroom/session/$sessionId': {
      id: '/classroom/session/$sessionId'
      path: '/classroom/session/$sessionId'
      fullPath: '/classroom/session/$sessionId'
      preLoaderRoute: typeof ClassroomSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom/preview/$lessonId': {
      id: '/classroom/preview/$lessonId'
      path: '/classroom/preview/$lessonId'
      fullPath: '/classroom/preview/$lessonId'
      preLoaderRoute: typeof ClassroomPreviewLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher/students': {
      id: '/_authenticated/teacher/students'
      path: '/teacher/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/settings': {
      id: '/_authenticated/teacher/settings'
      path: '/teacher/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof AuthenticatedTeacherSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/sessions': {
      id: '/_authenticated/teacher/sessions'
      path: '/teacher/sessions'
      fullPath: '/teacher/sessions'
      preLoaderRoute: typeof AuthenticatedTeacherSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/resources': {
      id: '/_authenticated/teacher/resources'
      path: '/teacher/resources'
      fullPath: '/teacher/resources'
      preLoaderRoute: typeof AuthenticatedTeacherResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/lessons': {
      id: '/_authenticated/teacher/lessons'
      path: '/teacher/lessons'
      fullPath: '/teacher/lessons'
      preLoaderRoute: typeof AuthenticatedTeacherLessonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/dashboard': {
      id: '/_authenticated/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof AuthenticatedTeacherDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/courses': {
      id: '/_authenticated/teacher/courses'
      path: '/teacher/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/analytics': {
      id: '/_authenticated/teacher/analytics'
      path: '/teacher/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof AuthenticatedTeacherAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/settings': {
      id: '/_authenticated/student/settings'
      path: '/student/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof AuthenticatedStudentSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/sessions': {
      id: '/_authenticated/student/sessions'
      path: '/student/sessions'
      fullPath: '/student/sessions'
      preLoaderRoute: typeof AuthenticatedStudentSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/search': {
      id: '/_authenticated/student/search'
      path: '/student/search'
      fullPath: '/student/search'
      preLoaderRoute: typeof AuthenticatedStudentSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/resources': {
      id: '/_authenticated/student/resources'
      path: '/student/resources'
      fullPath: '/student/resources'
      preLoaderRoute: typeof AuthenticatedStudentResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/quizzes': {
      id: '/_authenticated/student/quizzes'
      path: '/student/quizzes'
      fullPath: '/student/quizzes'
      preLoaderRoute: typeof AuthenticatedStudentQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/notifications': {
      id: '/_authenticated/student/notifications'
      path: '/student/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof AuthenticatedStudentNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/notes': {
      id: '/_authenticated/student/notes'
      path: '/student/notes'
      fullPath: '/student/notes'
      preLoaderRoute: typeof AuthenticatedStudentNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/messages': {
      id: '/_authenticated/student/messages'
      path: '/student/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof AuthenticatedStudentMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/lessons': {
      id: '/_authenticated/student/lessons'
      path: '/student/lessons'
      fullPath: '/student/lessons'
      preLoaderRoute: typeof AuthenticatedStudentLessonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/learning-plan': {
      id: '/_authenticated/student/learning-plan'
      path: '/student/learning-plan'
      fullPath: '/student/learning-plan'
      preLoaderRoute: typeof AuthenticatedStudentLearningPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/courses': {
      id: '/_authenticated/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof AuthenticatedStudentCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/classrooms': {
      id: '/_authenticated/student/classrooms'
      path: '/student/classrooms'
      fullPath: '/student/classrooms'
      preLoaderRoute: typeof AuthenticatedStudentClassroomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/calendar': {
      id: '/_authenticated/student/calendar'
      path: '/student/calendar'
      fullPath: '/student/calendar'
      preLoaderRoute: typeof AuthenticatedStudentCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/assignments': {
      id: '/_authenticated/student/assignments'
      path: '/student/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/achievements': {
      id: '/_authenticated/student/achievements'
      path: '/student/achievements'
      fullPath: '/student/achievements'
      preLoaderRoute: typeof AuthenticatedStudentAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/access': {
      id: '/_authenticated/student/access'
      path: '/student/access'
      fullPath: '/student/access'
      preLoaderRoute: typeof AuthenticatedStudentAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/teachers': {
      id: '/_authenticated/institution/teachers'
      path: '/institution/teachers'
      fullPath: '/institution/teachers'
      preLoaderRoute: typeof AuthenticatedInstitutionTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/students': {
      id: '/_authenticated/institution/students'
      path: '/institution/students'
      fullPath: '/institution/students'
      preLoaderRoute: typeof AuthenticatedInstitutionStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/settings': {
      id: '/_authenticated/institution/settings'
      path: '/institution/settings'
      fullPath: '/institution/settings'
      preLoaderRoute: typeof AuthenticatedInstitutionSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/sessions': {
      id: '/_authenticated/institution/sessions'
      path: '/institution/sessions'
      fullPath: '/institution/sessions'
      preLoaderRoute: typeof AuthenticatedInstitutionSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/resources': {
      id: '/_authenticated/institution/resources'
      path: '/institution/resources'
      fullPath: '/institution/resources'
      preLoaderRoute: typeof AuthenticatedInstitutionResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/enrollments': {
      id: '/_authenticated/institution/enrollments'
      path: '/institution/enrollments'
      fullPath: '/institution/enrollments'
      preLoaderRoute: typeof AuthenticatedInstitutionEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/dashboard': {
      id: '/_authenticated/institution/dashboard'
      path: '/institution/dashboard'
      fullPath: '/institution/dashboard'
      preLoaderRoute: typeof AuthenticatedInstitutionDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/courses': {
      id: '/_authenticated/institution/courses'
      path: '/institution/courses'
      fullPath: '/institution/courses'
      preLoaderRoute: typeof AuthenticatedInstitutionCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/classrooms': {
      id: '/_authenticated/institution/classrooms'
      path: '/institution/classrooms'
      fullPath: '/institution/classrooms'
      preLoaderRoute: typeof AuthenticatedInstitutionClassroomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/analytics': {
      id: '/_authenticated/institution/analytics'
      path: '/institution/analytics'
      fullPath: '/institution/analytics'
      preLoaderRoute: typeof AuthenticatedInstitutionAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/activity': {
      id: '/_authenticated/institution/activity'
      path: '/institution/activity'
      fullPath: '/institution/activity'
      preLoaderRoute: typeof AuthenticatedInstitutionActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/courses/$courseId': {
      id: '/_authenticated/teacher/courses/$courseId'
      path: '/$courseId'
      fullPath: '/teacher/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedTeacherCoursesRoute
    }
    '/_authenticated/student/settings/profile': {
      id: '/_authenticated/student/settings/profile'
      path: '/profile'
      fullPath: '/student/settings/profile'
      preLoaderRoute: typeof AuthenticatedStudentSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedStudentSettingsRoute
    }
    '/_authenticated/student/resources/$resourceId': {
      id: '/_authenticated/student/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/student/resources/$resourceId'
      preLoaderRoute: typeof AuthenticatedStudentResourcesResourceIdRouteImport
      parentRoute: typeof AuthenticatedStudentResourcesRoute
    }
    '/_authenticated/student/quizzes/$quizId': {
      id: '/_authenticated/student/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/student/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedStudentQuizzesQuizIdRouteImport
      parentRoute: typeof AuthenticatedStudentQuizzesRoute
    }
    '/_authenticated/student/notes/$noteId': {
      id: '/_authenticated/student/notes/$noteId'
      path: '/$noteId'
      fullPath: '/student/notes/$noteId'
      preLoaderRoute: typeof AuthenticatedStudentNotesNoteIdRouteImport
      parentRoute: typeof AuthenticatedStudentNotesRoute
    }
    '/_authenticated/student/lessons/$lessonId': {
      id: '/_authenticated/student/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/student/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedStudentLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedStudentLessonsRoute
    }
    '/_authenticated/student/courses/$courseId': {
      id: '/_authenticated/student/courses/$courseId'
      path: '/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedStudentCoursesRoute
    }
    '/_authenticated/student/ai-lesson/new': {
      id: '/_authenticated/student/ai-lesson/new'
      path: '/student/ai-lesson/new'
      fullPath: '/student/ai-lesson/new'
      preLoaderRoute: typeof AuthenticatedStudentAiLessonNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution/resources/upload': {
      id: '/_authenticated/institution/resources/upload'
      path: '/upload'
      fullPath: '/institution/resources/upload'
      preLoaderRoute: typeof AuthenticatedInstitutionResourcesUploadRouteImport
      parentRoute: typeof AuthenticatedInstitutionResourcesRoute
    }
    '/_authenticated/institution/courses/new': {
      id: '/_authenticated/institution/courses/new'
      path: '/new'
      fullPath: '/institution/courses/new'
      preLoaderRoute: typeof AuthenticatedInstitutionCoursesNewRouteImport
      parentRoute: typeof AuthenticatedInstitutionCoursesRoute
    }
    '/_authenticated/institution/courses/$courseId': {
      id: '/_authenticated/institution/courses/$courseId'
      path: '/$courseId'
      fullPath: '/institution/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedInstitutionCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedInstitutionCoursesRoute
    }
    '/_authenticated/teacher/lessons/$lessonId/edit': {
      id: '/_authenticated/teacher/lessons/$lessonId/edit'
      path: '/$lessonId/edit'
      fullPath: '/teacher/lessons/$lessonId/edit'
      preLoaderRoute: typeof AuthenticatedTeacherLessonsLessonIdEditRouteImport
      parentRoute: typeof AuthenticatedTeacherLessonsRoute
    }
    '/_authenticated/teacher/courses/$courseId/analytics': {
      id: '/_authenticated/teacher/courses/$courseId/analytics'
      path: '/analytics'
      fullPath: '/teacher/courses/$courseId/analytics'
      preLoaderRoute: typeof AuthenticatedTeacherCoursesCourseIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedTeacherCoursesCourseIdRoute
    }
    '/_authenticated/student/sessions/$sessionId/summary': {
      id: '/_authenticated/student/sessions/$sessionId/summary'
      path: '/$sessionId/summary'
      fullPath: '/student/sessions/$sessionId/summary'
      preLoaderRoute: typeof AuthenticatedStudentSessionsSessionIdSummaryRouteImport
      parentRoute: typeof AuthenticatedStudentSessionsRoute
    }
    '/_authenticated/student/sessions/$sessionId/replay': {
      id: '/_authenticated/student/sessions/$sessionId/replay'
      path: '/$sessionId/replay'
      fullPath: '/student/sessions/$sessionId/replay'
      preLoaderRoute: typeof AuthenticatedStudentSessionsSessionIdReplayRouteImport
      parentRoute: typeof AuthenticatedStudentSessionsRoute
    }
    '/_authenticated/student/courses/$courseId/lessons': {
      id: '/_authenticated/student/courses/$courseId/lessons'
      path: '/lessons'
      fullPath: '/student/courses/$courseId/lessons'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdLessonsRouteImport
      parentRoute: typeof AuthenticatedStudentCoursesCourseIdRoute
    }
  }
}

interface AuthenticatedInstitutionCoursesRouteChildren {
  AuthenticatedInstitutionCoursesCourseIdRoute: typeof AuthenticatedInstitutionCoursesCourseIdRoute
  AuthenticatedInstitutionCoursesNewRoute: typeof AuthenticatedInstitutionCoursesNewRoute
}

const AuthenticatedInstitutionCoursesRouteChildren: AuthenticatedInstitutionCoursesRouteChildren =
  {
    AuthenticatedInstitutionCoursesCourseIdRoute:
      AuthenticatedInstitutionCoursesCourseIdRoute,
    AuthenticatedInstitutionCoursesNewRoute:
      AuthenticatedInstitutionCoursesNewRoute,
  }

const AuthenticatedInstitutionCoursesRouteWithChildren =
  AuthenticatedInstitutionCoursesRoute._addFileChildren(
    AuthenticatedInstitutionCoursesRouteChildren,
  )

interface AuthenticatedInstitutionResourcesRouteChildren {
  AuthenticatedInstitutionResourcesUploadRoute: typeof AuthenticatedInstitutionResourcesUploadRoute
}

const AuthenticatedInstitutionResourcesRouteChildren: AuthenticatedInstitutionResourcesRouteChildren =
  {
    AuthenticatedInstitutionResourcesUploadRoute:
      AuthenticatedInstitutionResourcesUploadRoute,
  }

const AuthenticatedInstitutionResourcesRouteWithChildren =
  AuthenticatedInstitutionResourcesRoute._addFileChildren(
    AuthenticatedInstitutionResourcesRouteChildren,
  )

interface AuthenticatedStudentCoursesCourseIdRouteChildren {
  AuthenticatedStudentCoursesCourseIdLessonsRoute: typeof AuthenticatedStudentCoursesCourseIdLessonsRoute
}

const AuthenticatedStudentCoursesCourseIdRouteChildren: AuthenticatedStudentCoursesCourseIdRouteChildren =
  {
    AuthenticatedStudentCoursesCourseIdLessonsRoute:
      AuthenticatedStudentCoursesCourseIdLessonsRoute,
  }

const AuthenticatedStudentCoursesCourseIdRouteWithChildren =
  AuthenticatedStudentCoursesCourseIdRoute._addFileChildren(
    AuthenticatedStudentCoursesCourseIdRouteChildren,
  )

interface AuthenticatedStudentCoursesRouteChildren {
  AuthenticatedStudentCoursesCourseIdRoute: typeof AuthenticatedStudentCoursesCourseIdRouteWithChildren
}

const AuthenticatedStudentCoursesRouteChildren: AuthenticatedStudentCoursesRouteChildren =
  {
    AuthenticatedStudentCoursesCourseIdRoute:
      AuthenticatedStudentCoursesCourseIdRouteWithChildren,
  }

const AuthenticatedStudentCoursesRouteWithChildren =
  AuthenticatedStudentCoursesRoute._addFileChildren(
    AuthenticatedStudentCoursesRouteChildren,
  )

interface AuthenticatedStudentLessonsRouteChildren {
  AuthenticatedStudentLessonsLessonIdRoute: typeof AuthenticatedStudentLessonsLessonIdRoute
}

const AuthenticatedStudentLessonsRouteChildren: AuthenticatedStudentLessonsRouteChildren =
  {
    AuthenticatedStudentLessonsLessonIdRoute:
      AuthenticatedStudentLessonsLessonIdRoute,
  }

const AuthenticatedStudentLessonsRouteWithChildren =
  AuthenticatedStudentLessonsRoute._addFileChildren(
    AuthenticatedStudentLessonsRouteChildren,
  )

interface AuthenticatedStudentNotesRouteChildren {
  AuthenticatedStudentNotesNoteIdRoute: typeof AuthenticatedStudentNotesNoteIdRoute
}

const AuthenticatedStudentNotesRouteChildren: AuthenticatedStudentNotesRouteChildren =
  {
    AuthenticatedStudentNotesNoteIdRoute: AuthenticatedStudentNotesNoteIdRoute,
  }

const AuthenticatedStudentNotesRouteWithChildren =
  AuthenticatedStudentNotesRoute._addFileChildren(
    AuthenticatedStudentNotesRouteChildren,
  )

interface AuthenticatedStudentQuizzesRouteChildren {
  AuthenticatedStudentQuizzesQuizIdRoute: typeof AuthenticatedStudentQuizzesQuizIdRoute
}

const AuthenticatedStudentQuizzesRouteChildren: AuthenticatedStudentQuizzesRouteChildren =
  {
    AuthenticatedStudentQuizzesQuizIdRoute:
      AuthenticatedStudentQuizzesQuizIdRoute,
  }

const AuthenticatedStudentQuizzesRouteWithChildren =
  AuthenticatedStudentQuizzesRoute._addFileChildren(
    AuthenticatedStudentQuizzesRouteChildren,
  )

interface AuthenticatedStudentResourcesRouteChildren {
  AuthenticatedStudentResourcesResourceIdRoute: typeof AuthenticatedStudentResourcesResourceIdRoute
}

const AuthenticatedStudentResourcesRouteChildren: AuthenticatedStudentResourcesRouteChildren =
  {
    AuthenticatedStudentResourcesResourceIdRoute:
      AuthenticatedStudentResourcesResourceIdRoute,
  }

const AuthenticatedStudentResourcesRouteWithChildren =
  AuthenticatedStudentResourcesRoute._addFileChildren(
    AuthenticatedStudentResourcesRouteChildren,
  )

interface AuthenticatedStudentSessionsRouteChildren {
  AuthenticatedStudentSessionsSessionIdReplayRoute: typeof AuthenticatedStudentSessionsSessionIdReplayRoute
  AuthenticatedStudentSessionsSessionIdSummaryRoute: typeof AuthenticatedStudentSessionsSessionIdSummaryRoute
}

const AuthenticatedStudentSessionsRouteChildren: AuthenticatedStudentSessionsRouteChildren =
  {
    AuthenticatedStudentSessionsSessionIdReplayRoute:
      AuthenticatedStudentSessionsSessionIdReplayRoute,
    AuthenticatedStudentSessionsSessionIdSummaryRoute:
      AuthenticatedStudentSessionsSessionIdSummaryRoute,
  }

const AuthenticatedStudentSessionsRouteWithChildren =
  AuthenticatedStudentSessionsRoute._addFileChildren(
    AuthenticatedStudentSessionsRouteChildren,
  )

interface AuthenticatedStudentSettingsRouteChildren {
  AuthenticatedStudentSettingsProfileRoute: typeof AuthenticatedStudentSettingsProfileRoute
}

const AuthenticatedStudentSettingsRouteChildren: AuthenticatedStudentSettingsRouteChildren =
  {
    AuthenticatedStudentSettingsProfileRoute:
      AuthenticatedStudentSettingsProfileRoute,
  }

const AuthenticatedStudentSettingsRouteWithChildren =
  AuthenticatedStudentSettingsRoute._addFileChildren(
    AuthenticatedStudentSettingsRouteChildren,
  )

interface AuthenticatedTeacherCoursesCourseIdRouteChildren {
  AuthenticatedTeacherCoursesCourseIdAnalyticsRoute: typeof AuthenticatedTeacherCoursesCourseIdAnalyticsRoute
}

const AuthenticatedTeacherCoursesCourseIdRouteChildren: AuthenticatedTeacherCoursesCourseIdRouteChildren =
  {
    AuthenticatedTeacherCoursesCourseIdAnalyticsRoute:
      AuthenticatedTeacherCoursesCourseIdAnalyticsRoute,
  }

const AuthenticatedTeacherCoursesCourseIdRouteWithChildren =
  AuthenticatedTeacherCoursesCourseIdRoute._addFileChildren(
    AuthenticatedTeacherCoursesCourseIdRouteChildren,
  )

interface AuthenticatedTeacherCoursesRouteChildren {
  AuthenticatedTeacherCoursesCourseIdRoute: typeof AuthenticatedTeacherCoursesCourseIdRouteWithChildren
}

const AuthenticatedTeacherCoursesRouteChildren: AuthenticatedTeacherCoursesRouteChildren =
  {
    AuthenticatedTeacherCoursesCourseIdRoute:
      AuthenticatedTeacherCoursesCourseIdRouteWithChildren,
  }

const AuthenticatedTeacherCoursesRouteWithChildren =
  AuthenticatedTeacherCoursesRoute._addFileChildren(
    AuthenticatedTeacherCoursesRouteChildren,
  )

interface AuthenticatedTeacherLessonsRouteChildren {
  AuthenticatedTeacherLessonsLessonIdEditRoute: typeof AuthenticatedTeacherLessonsLessonIdEditRoute
}

const AuthenticatedTeacherLessonsRouteChildren: AuthenticatedTeacherLessonsRouteChildren =
  {
    AuthenticatedTeacherLessonsLessonIdEditRoute:
      AuthenticatedTeacherLessonsLessonIdEditRoute,
  }

const AuthenticatedTeacherLessonsRouteWithChildren =
  AuthenticatedTeacherLessonsRoute._addFileChildren(
    AuthenticatedTeacherLessonsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInstitutionActivityRoute: typeof AuthenticatedInstitutionActivityRoute
  AuthenticatedInstitutionAnalyticsRoute: typeof AuthenticatedInstitutionAnalyticsRoute
  AuthenticatedInstitutionClassroomsRoute: typeof AuthenticatedInstitutionClassroomsRoute
  AuthenticatedInstitutionCoursesRoute: typeof AuthenticatedInstitutionCoursesRouteWithChildren
  AuthenticatedInstitutionDashboardRoute: typeof AuthenticatedInstitutionDashboardRoute
  AuthenticatedInstitutionEnrollmentsRoute: typeof AuthenticatedInstitutionEnrollmentsRoute
  AuthenticatedInstitutionResourcesRoute: typeof AuthenticatedInstitutionResourcesRouteWithChildren
  AuthenticatedInstitutionSessionsRoute: typeof AuthenticatedInstitutionSessionsRoute
  AuthenticatedInstitutionSettingsRoute: typeof AuthenticatedInstitutionSettingsRoute
  AuthenticatedInstitutionStudentsRoute: typeof AuthenticatedInstitutionStudentsRoute
  AuthenticatedInstitutionTeachersRoute: typeof AuthenticatedInstitutionTeachersRoute
  AuthenticatedStudentAccessRoute: typeof AuthenticatedStudentAccessRoute
  AuthenticatedStudentAchievementsRoute: typeof AuthenticatedStudentAchievementsRoute
  AuthenticatedStudentAssignmentsRoute: typeof AuthenticatedStudentAssignmentsRoute
  AuthenticatedStudentCalendarRoute: typeof AuthenticatedStudentCalendarRoute
  AuthenticatedStudentClassroomsRoute: typeof AuthenticatedStudentClassroomsRoute
  AuthenticatedStudentCoursesRoute: typeof AuthenticatedStudentCoursesRouteWithChildren
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentLearningPlanRoute: typeof AuthenticatedStudentLearningPlanRoute
  AuthenticatedStudentLessonsRoute: typeof AuthenticatedStudentLessonsRouteWithChildren
  AuthenticatedStudentMessagesRoute: typeof AuthenticatedStudentMessagesRoute
  AuthenticatedStudentNotesRoute: typeof AuthenticatedStudentNotesRouteWithChildren
  AuthenticatedStudentNotificationsRoute: typeof AuthenticatedStudentNotificationsRoute
  AuthenticatedStudentQuizzesRoute: typeof AuthenticatedStudentQuizzesRouteWithChildren
  AuthenticatedStudentResourcesRoute: typeof AuthenticatedStudentResourcesRouteWithChildren
  AuthenticatedStudentSearchRoute: typeof AuthenticatedStudentSearchRoute
  AuthenticatedStudentSessionsRoute: typeof AuthenticatedStudentSessionsRouteWithChildren
  AuthenticatedStudentSettingsRoute: typeof AuthenticatedStudentSettingsRouteWithChildren
  AuthenticatedTeacherAnalyticsRoute: typeof AuthenticatedTeacherAnalyticsRoute
  AuthenticatedTeacherCoursesRoute: typeof AuthenticatedTeacherCoursesRouteWithChildren
  AuthenticatedTeacherDashboardRoute: typeof AuthenticatedTeacherDashboardRoute
  AuthenticatedTeacherLessonsRoute: typeof AuthenticatedTeacherLessonsRouteWithChildren
  AuthenticatedTeacherResourcesRoute: typeof AuthenticatedTeacherResourcesRoute
  AuthenticatedTeacherSessionsRoute: typeof AuthenticatedTeacherSessionsRoute
  AuthenticatedTeacherSettingsRoute: typeof AuthenticatedTeacherSettingsRoute
  AuthenticatedTeacherStudentsRoute: typeof AuthenticatedTeacherStudentsRoute
  AuthenticatedStudentAiLessonNewRoute: typeof AuthenticatedStudentAiLessonNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInstitutionActivityRoute: AuthenticatedInstitutionActivityRoute,
  AuthenticatedInstitutionAnalyticsRoute:
    AuthenticatedInstitutionAnalyticsRoute,
  AuthenticatedInstitutionClassroomsRoute:
    AuthenticatedInstitutionClassroomsRoute,
  AuthenticatedInstitutionCoursesRoute:
    AuthenticatedInstitutionCoursesRouteWithChildren,
  AuthenticatedInstitutionDashboardRoute:
    AuthenticatedInstitutionDashboardRoute,
  AuthenticatedInstitutionEnrollmentsRoute:
    AuthenticatedInstitutionEnrollmentsRoute,
  AuthenticatedInstitutionResourcesRoute:
    AuthenticatedInstitutionResourcesRouteWithChildren,
  AuthenticatedInstitutionSessionsRoute: AuthenticatedInstitutionSessionsRoute,
  AuthenticatedInstitutionSettingsRoute: AuthenticatedInstitutionSettingsRoute,
  AuthenticatedInstitutionStudentsRoute: AuthenticatedInstitutionStudentsRoute,
  AuthenticatedInstitutionTeachersRoute: AuthenticatedInstitutionTeachersRoute,
  AuthenticatedStudentAccessRoute: AuthenticatedStudentAccessRoute,
  AuthenticatedStudentAchievementsRoute: AuthenticatedStudentAchievementsRoute,
  AuthenticatedStudentAssignmentsRoute: AuthenticatedStudentAssignmentsRoute,
  AuthenticatedStudentCalendarRoute: AuthenticatedStudentCalendarRoute,
  AuthenticatedStudentClassroomsRoute: AuthenticatedStudentClassroomsRoute,
  AuthenticatedStudentCoursesRoute:
    AuthenticatedStudentCoursesRouteWithChildren,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentLearningPlanRoute: AuthenticatedStudentLearningPlanRoute,
  AuthenticatedStudentLessonsRoute:
    AuthenticatedStudentLessonsRouteWithChildren,
  AuthenticatedStudentMessagesRoute: AuthenticatedStudentMessagesRoute,
  AuthenticatedStudentNotesRoute: AuthenticatedStudentNotesRouteWithChildren,
  AuthenticatedStudentNotificationsRoute:
    AuthenticatedStudentNotificationsRoute,
  AuthenticatedStudentQuizzesRoute:
    AuthenticatedStudentQuizzesRouteWithChildren,
  AuthenticatedStudentResourcesRoute:
    AuthenticatedStudentResourcesRouteWithChildren,
  AuthenticatedStudentSearchRoute: AuthenticatedStudentSearchRoute,
  AuthenticatedStudentSessionsRoute:
    AuthenticatedStudentSessionsRouteWithChildren,
  AuthenticatedStudentSettingsRoute:
    AuthenticatedStudentSettingsRouteWithChildren,
  AuthenticatedTeacherAnalyticsRoute: AuthenticatedTeacherAnalyticsRoute,
  AuthenticatedTeacherCoursesRoute:
    AuthenticatedTeacherCoursesRouteWithChildren,
  AuthenticatedTeacherDashboardRoute: AuthenticatedTeacherDashboardRoute,
  AuthenticatedTeacherLessonsRoute:
    AuthenticatedTeacherLessonsRouteWithChildren,
  AuthenticatedTeacherResourcesRoute: AuthenticatedTeacherResourcesRoute,
  AuthenticatedTeacherSessionsRoute: AuthenticatedTeacherSessionsRoute,
  AuthenticatedTeacherSettingsRoute: AuthenticatedTeacherSettingsRoute,
  AuthenticatedTeacherStudentsRoute: AuthenticatedTeacherStudentsRoute,
  AuthenticatedStudentAiLessonNewRoute: AuthenticatedStudentAiLessonNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClassroomDesignLessonIdRoute: ClassroomDesignLessonIdRoute,
  ClassroomEnhancedLessonIdRoute: ClassroomEnhancedLessonIdRoute,
  ClassroomLessonIdRoute: ClassroomLessonIdRoute,
  DemoClassroomRoute: DemoClassroomRoute,
  InstitutionsRegisterRoute: InstitutionsRegisterRoute,
  StudentProgressRoute: StudentProgressRoute,
  ClassroomPreviewLessonIdRoute: ClassroomPreviewLessonIdRoute,
  ClassroomSessionSessionIdRoute: ClassroomSessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
