// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/** Demo context returned when Supabase is not configured. */
function demoContext() {
  return {
    supabase: null as any,
    userId: "demo-user-0000",
    claims: { sub: "demo-user-0000", email: "demo@klassruum.com" } as any,
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }): Promise<any> => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    // ── Demo mode: Supabase not configured ──────────────────────────────
    if (
      !SUPABASE_URL ||
      !SUPABASE_PUBLISHABLE_KEY ||
      SUPABASE_URL.includes("demo.supabase") ||
      SUPABASE_PUBLISHABLE_KEY.includes("demo_key")
    ) {
      return next({ context: demoContext() });
    }

    const request = getRequest();

    if (!request?.headers) {
      return next({ context: demoContext() });
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return next({ context: demoContext() });
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      return next({ context: demoContext() });
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      return next({ context: demoContext() });
    }

    if (!data.claims.sub) {
      return next({ context: demoContext() });
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
